apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: xinchaoduyanh2/fe:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: fe-config
            - secretRef:
                name: fe-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  selector:
    app: fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
